spring.application.name=orbiteye-api
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM560494
spring.datasource.password=180606
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# IMPORTANTE:
# none = o Hibernate usa as tabelas existentes e nao tenta alterar/criar estrutura.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cache.type=simple

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# Desativa chamada real da OpenAI para rodar sem API Key
spring.ai.openai.api-key=dummy-key
spring.ai.openai.chat.enabled=false
spring.ai.openai.audio.speech.enabled=false
spring.ai.openai.audio.transcription.enabled=false
spring.ai.openai.embedding.enabled=false
spring.ai.openai.image.enabled=false